apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: app-deploy
spec:
  resources:
    - name: pipeline-resource-type
      type: pipeline-type
  tasks:
    - name: taskName
      taskRef:
        name: build-app